// <auto-generated />
namespace PIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_note_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_note_column));
        
        string IMigrationMetadata.Id
        {
            get { return "202012221209535_add_note_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
